### ISSUE TITLE
404 Not Found: com.hutchind.cordova.plugins.streamingmedia@~0.1.4

### ISSUE THREAD

**Issue by 13122310958** [nchutchind/cordova-plugin-streaming-media#102]
404 Not Found: com.hutchind.cordova.plugins.streamingmedia@~0.1.4

how to solve it ? could you hell me? thanks.

**Comment by 13122310958** [comment]
resolve by myself . 

remove  it in my package.json  , then
npm  uninstall --save com.hutchind.cordova.plugins.streamingmedia 

Boom!

**Comment by jim1924** [comment]
I really don't know how to thank you!!!!!!!! YOU SAVED MY LIFE!!!!!!

**Comment by stefinouleho** [comment]
you save my life too. thanks ☺️☺️☺️☺️

**Comment by notonlybutalso** [comment]
This plugin just seems to always set errors going in my Ionic 3 project due to a naming mismatch.

Adding the plugin we use: cordova-plugin-streaming-media
And its installing as: com.hutchind.cordova.plugins.streamingmedia

The 404 errors then start appearing and are stopping my Ionic project from compiling in the Ionic 'store'.

Any answers would be greatly appreciated! :-)

**Comment by einfochips1** [comment]
@notonlybutalso try this solution, it works for me in ionic-3
https://github.com/nchutchind/cordova-plugin-streaming-media/issues/104
