### ISSUE TITLE
Error npm registry

### ISSUE THREAD

**Issue by valderind4** [nchutchind/cordova-plugin-streaming-media#104]
I have this issue using this plugin on Ionic development:

Failed to restore plugin "com.hutchind.cordova.plugins.streamingmedia" from conf
ig.xml. You might need to try adding it again. Error: Failed to fetch plugin com
.hutchind.cordova.plugins.streamingmedia@~0.1.4 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "com.hutchind.cordova.plugins.stre
amingmedia@~0.1.4"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/com.hut
chind.cordova.plugins.streamingmedia
npm ERR! 404
npm ERR! 404  'com.hutchind.cordova.plugins.streamingmedia' is not in the npm re
gistry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Can someone help me?

**Comment by Arathmorr** [comment]
Which npm version are you using? I had this and downgraded back to 5.3.0 which seemed to solve the problem.

**Comment by tiagomsmagalhaes** [comment]
@valderind4 I also have this issue when wanting to remove other plugin..

@nchutchind is there any issue in npmjs?

**Comment by satish-nikam** [comment]
Any workaround to fix this? I can remove wrong entry from config.xml/package.json, but they are added again when I rebuild.

**Comment by tomercagan** [comment]
Hi, 

I have the same issue - any command that changes plugin/platform causes this error to appear and the command to fail. 

For example:
* `cordova build` - it is not able to restore the plugin with this 404 error (I pasted it again below in qouted test format because it is easier to read)
* After installing this plugin + additional one, trying to `cordova plugin rm cordova-plugin-other` results in this error and the plugin not removed.
* When trying to remove the plugin, if I use `cordova-plugin-streaming-media` then I get the error, it will only be removed if using the 'old' name (`com.hutchind.cordova.plugins.streamingmedia`)


> Error: cmd: Command failed with exit code 1 Error output:
> npm ERR! code E404
> npm ERR! 404 Not Found: com.hutchind.cordova.plugins.streamingmedia@~0.1.4
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\yourusername\AppData\Roaming\npm-cache\_logs\2017-11-18T13_14_19_729Z-debug.log

Note that I installed the plugin using `cordova plugin add cordova-plugin-streaming-media`. I believe that this issue, as well as #102 are caused by some discrepancy between the plugin name and the id (com.abc.edf vs cordova-plugin-edf)

I am not that familiar with writing plugins but if I can somehow help with this - I'd be happy to.

**Comment by atayahmet** [comment]
Hi, 

I fixed it in the follwing way as temporary solve:

**package.json**
```javascript
"com.hutchind.cordova.plugins.streamingmedia": "git+https://github.com/nchutchind/cordova-plugin-streaming-media.git"
```

**Comment by tiagomsmagalhaes** [comment]
@atayahmet that solve doesn't get overwritten?

**Comment by tomercagan** [comment]
@atayahmet - in what package.json do you mean to make the change in? Also, a best course would be that the library is updated (but not really sure what/where to change it)

**Comment by burakodabas** [comment]
@atayahmet Woow ! thank you Ahmet :) işe yaradı ve çok işimi gördü teşekkür ederim

**Comment by CharanRoot** [comment]
changing all reference of "com.hutchind.cordova.plugins.streamingmedia" to "cordova-plugin-streaming-media" in package.json, config.xml fixed issue.

https://github.com/nchutchind/cordova-plugin-streaming-media/issues/72#issuecomment-341453423

**Comment by hammondwb** [comment]
@CharanRoot This worked for me!

**Comment by ludobit** [comment]
@Jule- cordova is let to itself, move on different technologies (as ReactNative or Flutter)

**Comment by shamilovtim** [comment]
I am still maintaining the repo, for now but yes Cordova does look slightly at risk, sadly.

**Comment by Jule-** [comment]
@shamilovtim at least can you publish a new npm version reflecting last changes? I mean if you are still maintaining the repo this is the right thing to do. If not you should advise devs in the readme.
Thanks for the others.

**Comment by shamilovtim** [comment]
we'll generate a new NPM version soon
